name: vocab_builder_app
description: "A new Flutter project to build and review vocabulary."
# Prevent accidental publishing to pub.dev.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  uuid: ^4.3.3

  # Notifications
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2

  # Networking
  http: ^1.2.1

  # Offline Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3

  # Persistent Key-Value Storage
  shared_preferences: ^2.2.3

  # Connectivity
  connectivity_plus: ^7.0.0

  # File Operations & Sharing
  share_plus: ^7.2.2
  file_picker: ^10.3.3

  # Desktop support for file picker
  file_picker_desktop: ^1.2.0

  # UI & Fonts
  google_fonts: ^6.2.1
  flip_card: ^0.7.0

  # Text-to-Speech & Internationalization
  flutter_tts: ^4.0.2
  intl: ^0.20.2

  # Spaced Repetition Algorithm
  fsrs: ^2.0.1
  json_annotation: ^4.9.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linters
  flutter_lints: ^3.0.2

  # Code Generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  
  # App Icon & Splash Screen Generation
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.0

# Flutter-specific configurations
flutter:
  uses-material-design: true

  # Asset declaration to include all necessary files
  assets:
    - assets/data/
    - assets/icon.png

  # Font declaration for the local Inter font
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
          style: italic

# Configuration for flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

# Configuration for flutter_native_splash
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon.png
  color_dark: "#121212"
  image_dark: "assets/icon.png"
